
services:    
  basededonnees:
    image: mysql:5.7  
    environment:
      MYSQL_ROOT_PASSWORD: admin0712
      MYSQL_DATABASE: Bd_Wordpress 
      MYSQL_USER: Utilisateur_Aman 
      MYSQL_PASSWORD: kramo       
    volumes:                     
      - bd:/var/lib/mysql        
  wordpress:     
    depends_on:  
      - basededonnees  
    image: wordpress:latest 
    ports:
      - "2000:80" 
    environment:  
      WORDPRESS_DB_HOST: basededonnees
      WORDPRESS_DB_USER: Utilisateur_Aman
      WORDPRESS_DB_PASSWORD: kramo
      WORDPRESS_DB_NAME: Bd_Wordpress
    volumes:
      - wordpress_donnees:/var/www/html

volumes:
  bd:      
  wordpress_donnees:  
